// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc88k-b4NVcYHkjSrOm3lJHXCw1Rj1MjM',
    appId: '1:755742981907:web:c4c2a0d0ee0ff561fee4e6',
    messagingSenderId: '755742981907',
    projectId: 'mabibliothequeflutter',
    authDomain: 'mabibliothequeflutter.firebaseapp.com',
    storageBucket: 'mabibliothequeflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlKKOIpkO-46sCavCxZsXdqUOC6QSKaY',
    appId: '1:755742981907:android:90b89fcfc7bc4c2dfee4e6',
    messagingSenderId: '755742981907',
    projectId: 'mabibliothequeflutter',
    storageBucket: 'mabibliothequeflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOt807lNZF3bbP3WcBU4Z5Yrr98N5Q0bU',
    appId: '1:755742981907:ios:563f99209d2d003efee4e6',
    messagingSenderId: '755742981907',
    projectId: 'mabibliothequeflutter',
    storageBucket: 'mabibliothequeflutter.appspot.com',
    iosBundleId: 'com.example.maBibliothequeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOt807lNZF3bbP3WcBU4Z5Yrr98N5Q0bU',
    appId: '1:755742981907:ios:563f99209d2d003efee4e6',
    messagingSenderId: '755742981907',
    projectId: 'mabibliothequeflutter',
    storageBucket: 'mabibliothequeflutter.appspot.com',
    iosBundleId: 'com.example.maBibliothequeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc88k-b4NVcYHkjSrOm3lJHXCw1Rj1MjM',
    appId: '1:755742981907:web:9582c6f7a4332cd2fee4e6',
    messagingSenderId: '755742981907',
    projectId: 'mabibliothequeflutter',
    authDomain: 'mabibliothequeflutter.firebaseapp.com',
    storageBucket: 'mabibliothequeflutter.appspot.com',
  );
}
